site_name: Thais Carvalho
site_description: Portifólio da Thais Carvalho
site_url: ''
theme:
  name: material
  #custom_dir: overrides
  font:
    code: Roboto Mono
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: pink
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - search.share
    - search.suggest
    - navigation.expand
    - navigation.top
    - header.autohide
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/menina.png
  favicon: img/favicon.ico
  language: en
repo_name: 'thaisperlho'
repo_url: 'https://github.com/thaisperlho'
edit_uri: ''
plugins:
  - glightbox
  - search
  - mkdocs-video:
      mark: "custom-marker"

nav:
- Home: index.md
#- Instance Project: instance-project.md
- Meus projetos: 
  - Encontrando Caramelos: projetos/projeto1.md
  - Soccer News: projetos/projeto2.md
  - Projeto3: projetos/projeto3.md
  
- API:
  - Rest API: api/api1.md
  
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - attr_list
  - codehilite
  - extra
  - pymdownx.tabbed
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_div_format ''
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/twitterbrasil
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thais-perlho
copyright: Copyright &copy; Thais Pereira de Carvalho

extra_css:
  - css/termynal.css
  - css/custom.csss
  - css/extras.css

extra_javascript:
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/termynal.js
  - js/custom.js
  - js/table.js